### ISSUE TITLE
Not working on macOS Monterey

### ISSUE THREAD

**Issue by BrainMotto** [idcrook/s3d-thumbnail-generator-macos#1]
Hi,

I've updated the MacOS for Monterey and now it's not working.
Both accessibility and Screen Recording are enabled for S3D and nothing happens for some reason, at least for me.
I tried many times to run from terminal and runs without issues, naturally given the proper system permissions.
It's been some time since S3D is not updated, so maybe this is an S3D issue, but not sure.
Anyone else faced the same issue?

Many Thanks!

**Comment by idcrook** [comment]
Any time I have encountered similar problem, it was related to Simplify3D config.

what is exact text from "Additional terminal commands for post processing"?

what do the debugging files in the INSTALL_DIR reveal?

**Comment by BrainMotto** [comment]
Hi,
I have the following in the "Additional terminal commands for post
processing":

*/Users/<myusername>/Programming/3dprint/s3d-thumbnail-generator-macos/generate_S3D_thumbnails.bash
"[output_filepath]" &&*

*curl -k -H "X-Api-Key:<APIKEY>" -F "select=false" -F "print=false" -F
***@***.***_filepath]" "http://<hostname>:880/api/files/local*

It was working flawlessly before the MacOS Upgrade.
No reason for it to fail, but today guess what... It magically works,
without any changes... Seriously. Just rebooted the computer today and it's
working like in Big Sur.
Anyway, sorry for bothering you for nothing and btw very helpfull script of
yours!

Thanks and sorry for bothering you...

Best Regards

Em seg., 23 de mai. de 2022 às 10:06, David Crook ***@***.***>
escreveu:

**Comment by idcrook** [comment]
Cannot reproduce
