### ISSUE TITLE
Randomly working on MacOS BigSUR

### ISSUE THREAD

**Issue by bolsoncerrado** [idcrook/s3d-thumbnail-generator-macos#2]
Howdy,

I'm trying this in our raspberry pi-driven Prusa MK3S farm but I find it odd: the thumbnail generation works fine up to where I know (I can open both .gcode files and both have the thumbnail code inside), but once I upload them to the SHARED uploads folder all raspberries look at, some thumbnails show up, some don't and the ones that show up on one raspberry show as broken on another :?

Any clues what could be going on here?

<img width="1934" alt="Captura de pantalla 2022-11-30 a las 13 05 55" src="https://user-images.githubusercontent.com/10992914/204793044-7c8c313e-4c40-401c-9f43-32ba7674781a.png">

In this screenshot you can see top left most "octoprint" had ROBOCOP AUTO9 uploaded and thumbnail displaying fine.
To its right you can see the call to the thumbnail from the octoprint file icon and it won't load the thumbnail.
And on the lower row I uploaded COLT MKIV which has thumbnails on the gcode but its not detected by octoprint.

Yes, ALL instances have Slicer Thumbnails plugin enabled and I've already tried restarting/rebooting the PIs... 

Any clues?

Thanks!

**Comment by idcrook** [comment]
I really don't know, but it looks like this project is inserting the thumbnails OK into the file. 

Have you had a chance to look at the octoprint / octoprint plugin logs in the logfile? maybe try to compare between the two hosts?  

Also it's been a while since I cracked this open, but I would start looking at differences between the octopi hosts. maybe a missing python module or versioning thing or other some such thing? Perhaps a uninstall/reinstall of the Slicer Thumbnails plugin? Sorry if this is not more helpful.

**Comment by bolsoncerrado** [comment]
Thanks for the input.

In fact all raspis run the same OctoPi image and have been aptupdate/upgraded recently...

Yeah I guess I need to check the logs but....oh well.


Thanks.

**Comment by bolsoncerrado** [comment]
Finally fixed it thanks to @jneillls input re sharing the same thumbnail folder across the network :)




OH btw just 1 more thing now that we are at it :P 

How do I "move" the captured frame a bit lower? I've read the docs about which lines to edit on the bash script but I cant understand the logic behind it.

So say I have this thumbnail:


<img width="200" alt="TEC 9" src="https://user-images.githubusercontent.com/10992914/204889490-cf284727-b512-4d30-821d-03105ec35847.png">


...but I want to take the "snapshot" somewhat lower so all the bed gets in the pic.... 


How would I edit the height line on the bash script?


Thanks!

**Comment by idcrook** [comment]
It's highly dependent on your windowing and desktop setup and you need to customize to match your environment. I'd recommend manually running the script (in a shell window outside of simplify3d workflow itself) to iterate on experimenting with values until you find something that matches your preferences.

https://github.com/idcrook/s3d-thumbnail-generator-macos/blob/458f9026aebf29afa188f2151d33b6a5b9130e41/generate_S3D_thumbnails.bash#L113-L130
