### ISSUE TITLE
Support for Simplify3D v5?

### ISSUE THREAD

**Issue by bolsoncerrado** [idcrook/s3d-thumbnail-generator-macos#3]
I guess it's too early to report? LOL

LMK if I can be of help troubleshooting this one. So far, window title hasn't changed afaik so I'm puzzled as why it won't work anymore.

**Comment by bolsoncerrado** [comment]
This is what I'm getting parsed with v5:

<img width="376" alt="Captura de pantalla 2023-01-04 a las 10 48 14" src="https://user-images.githubusercontent.com/10992914/210528128-b6d2ae04-0036-4dd9-865e-5e9d15885eda.png">


@idcrook  any clues how to start troubleshooting this?

**Comment by bolsoncerrado** [comment]
OK hold on tight. Seems command tools wasnt installed in the new mac in the end LOL

Will report back asap.

**Comment by bolsoncerrado** [comment]
I forced reinstall imagemagik and getwindowID but nothing's saved on the file :(

**Comment by idcrook** [comment]
I don't have Simplify3D 5 (yet?) but my guess would be that the bundle identifier changed from 4 to 5.  If that is what happened, the `winidinfo=` line in the script would need to be updated to match.

https://github.com/idcrook/s3d-thumbnail-generator-macos/blob/458f9026aebf29afa188f2151d33b6a5b9130e41/generate_S3D_thumbnails.bash#L61-L65

**Comment by bolsoncerrado** [comment]
AFAIK visually it still displays as "Simplify3D (Licensed to Firstname Lastname)"

Perhaps it's the getwindowID script the one having issues? Any way to test it out? from the command line?

**Comment by idcrook** [comment]
Here's an example to run from command line:

```
❯ GetWindowID Safari --list
"" size=760x459 id=2928
"[BUG] Ain't working with Simplify3D v5 · Issue #3 · idcrook/s3d-thumbnail-generator-macos" size=1834x1311 id=2137
```

Run without any arguments to get its help message.

**Comment by bolsoncerrado** [comment]
alex@Mac-Studio ~ % GetWindowID Simplify3D --list
"(null)" size=294x687 id=3651
"(null)" size=2880x1490 id=3454
"(null)" size=0x0 id=3456



So it works!?

EDIT: Tried with | grep Simplify3D and it worked too, the 2880x1490 one only popped in.

**Comment by idcrook** [comment]
Apparently something is different on your host machine. `GetWindowID` looks like this on my machine. 

```
❯ GetWindowID Simplify3D --list
"(null)" size=0x0 id=6583
"Simplify3D (Licensed to *** ***)" size=1200x828 id=6582
```

I don't know about the macOS details to know why.  An initial guess would be security and privacy settings for terminal app that you use? I have my Mac in developer mode and the terminal app on full filesystem access settings, so could be something like that.  I don't know.

**Comment by bolsoncerrado** [comment]
alex@Mac-Studio ~ % GetWindowID Simplify3D --list | grep Simplify3D                                             
"filename (modified) - Simplify3D (Licensed to Xxxxxxxxx Xxxxxx)" size=2880x1490 id=3454
alex@Mac-Studio ~ % 


This is what I get. Is that incorrect?

**Comment by idcrook** [comment]
> alex@Mac-Studio ~ % GetWindowID Simplify3D --list | grep Simplify3D "filename (modified) - Simplify3D (Licensed to Xxxxxxxxx Xxxxxx)" size=2880x1490 id=3454 alex@Mac-Studio ~ %
> 
> This is what I get. Is that incorrect?

https://github.com/idcrook/s3d-thumbnail-generator-macos#enable-script-tracing

**Comment by idcrook** [comment]
>  An initial guess would be security and privacy settings for terminal app that you use? I have my Mac in developer mode and the terminal app on full filesystem access settings, so could be something like that. I don't know.

The following is copied directly from the `README.md`

-----

**IMPORTANT**: For recent macOS, in *System Preferences* in the *Security and Privacy* preferences, in the *Privacy* tab, you will have to enable **Screen Recording** (and possibly **Accessibility**) permissions for **`Simplify3D.app`**

   - This is so the post-processing script can automatically screen capture the Simplify3D app window

 - The preview thumbnail is obtained directly from the Simplify3D application window.

**Comment by bolsoncerrado** [comment]
Here's the output:

> alex@Mac-Studio s3d-thumbnails % echo END >! sample.gcode && ./generate_S3D_thumbnails.bash
400x469 237992

```
+ SCREENCAPTURE=/usr/sbin/screencapture
+ BASE64=/usr/bin/base64
+ bpfix=/usr/local
+ '[' -x /opt/homebrew/bin/brew ']'
+ GETWINDOWID=/usr/local/bin/GetWindowID
+ CONVERT=/usr/local/bin/convert
+ IDENTIFY=/usr/local/bin/identify
++ dirname ./generate_S3D_thumbnails.bash
+ INSTALL_DIR=./
+ GCODE=sample.gcode
+ WORKDIR=/var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/
+ RETINA_2X_MODE_DETECTED=0
+ DEFAULT_APP_WIDTH=1100
+ DEFAULT_APP_HEIGHT=775
++ shopt -po xtrace
+ TRACESTATE='set -o xtrace'
+ touch ./runtimestamp
+ [[ set -o xtrace == \s\e\t\ \-\o\ \x\t\r\a\c\e ]]
+ echo
+ echo /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/
+ echo sample.gcode
++ /usr/local/bin/GetWindowID Simplify3D --list
++ grep Simplify3D
+ winidinfo='"Simplify3D (Licensed to ***** ******)" size=2880x1490 id=11132'
+ '[' 0 -eq 1 ']'
+ [[ "Simplify3D (Licensed to ***** ******)" size=2880x1490 id=11132 =~ size=([0-9]+)x([0-9]+) ]]
+ appwidth=2880
+ appheight=1490
+ [[ "Simplify3D (Licensed to ***** ******)" size=2880x1490 id=11132 =~ id=([0-9]+) ]]
+ winid=11132
+ [[ "Simplify3D (Licensed to ***** ******)" size=2880x1490 id=11132 =~ "([^"]+)" ]]
+ wintitle='Simplify3D (Licensed to ***** ******)'
+ /usr/sbin/screencapture -x -o -l11132 /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png
++ /usr/local/bin/identify -ping -format '%[w]' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png
+ winpngdimw=5760
++ /usr/local/bin/identify -ping -format '%[h]' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png
+ winpngdimh=2980
+ [[ 5760 == 5760 ]]
+ [[ 2980 == 2980 ]]
+ RETINA_2X_MODE_DETECTED=1
+ echo RETINA_2X_MODE_DETECTED=1
RETINA_2X_MODE_DETECTED=1
+ cropw=2468
+ croph=1639
+ cropwinset=1728
+ crophinset=596
+ /usr/local/bin/convert /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png -crop 2468x1639+1728+596 /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/cropped.png
+ echo ''
+ /usr/local/bin/convert /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/cropped.png -resize 32x32 /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/sm_thumb.png
+ set +o xtrace
base64: invalid argument /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/sm_thumb.png
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
+ /usr/local/bin/convert /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/cropped.png -resize 400x /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/bigthumb.png
++ /usr/local/bin/identify -ping -format '%[w]x%[h]' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/bigthumb.png
+ bigthumbdim=400x266
+ set +o xtrace
base64: invalid argument /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/bigthumb.png
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
400x266 0
+ sed -i '' 's/^/; /' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/base64.txt
+ cat /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/base64.txt sample.gcode
+ mv /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/newFile.gcode sample.gcode
zsh: command not found: 400x469
alex@Mac-Studio s3d-thumbnails % 
```

**Comment by bolsoncerrado** [comment]
Are the basse64: invalid argument errors coming from the script being run on Terminal?

**Comment by bolsoncerrado** [comment]
Yes, both S3D and Terminal are enabled to record screen on Privacy settings....

**Comment by idcrook** [comment]
You entered in the wrong command for one. Should be the following for the sample debug command (notice no arguments to `generate_S3D_thumbnails.bash`) that will assumes the input file name `sample.gcode`

```
echo END >! sample.gcode && ./generate_S3D_thumbnails.bash
```

Also you can leave on the command tracing output by commenting out this line to see what command(s) get issued.

https://github.com/idcrook/s3d-thumbnail-generator-macos/blob/e59a7cf81d813e30eba46120a63001400b33dc6b/generate_S3D_thumbnails.bash#L138

**Comment by idcrook** [comment]
It looks like it was basically working up until that point in your output? All the script does is insert some specially encoded text into the gcode file. you can view the contents of the .gcode file in any text editor.

**Comment by idcrook** [comment]
> Yes, both S3D and Terminal are enabled to record screen on Privacy settings....

I've noticed for some apps that the permissions may need to removed and re-added for some applications when the apps are updated, but who knows...

**Comment by idcrook** [comment]
I am able to reproduce this `base64` error on my Mac (Ventura, Simplify3D 5) so stay tuned.

**Comment by idcrook** [comment]
I don't know if this is Ventura thing or what, but apparently `base64` needs a `-i/--input` argument now.

I pushed a fix with this to the `main` branch just now.  It fixed this same problem you were encountering for me. You should be able to git `pull` my updates. It was simply adding a `-i` before the filenames in the base64 commands

**Comment by bolsoncerrado** [comment]
Awesome! Let me try!

**Comment by bolsoncerrado** [comment]
BINGO! 

Works again and thumbnails are now placed correctly into the gcode.


Now for the more worrysome [compatibility with S3Dv5](https://github.com/idcrook/s3d-thumbnail-generator-macos/issues/4).... :/
