### ISSUE TITLE
Simplify3D: Postprocessing script not executing on S3D v5 where it worked on v4

### ISSUE THREAD

**Issue by bolsoncerrado** [idcrook/s3d-thumbnail-generator-macos#4]
So apparently "something" else has changed as S3D v5 won't open ANY of the gcodes containing thumbnails generated by v4 and the scripts.

O - U - C - H - ! 

:'(

**Comment by idcrook** [comment]
sounds like you may want to contact Simplify3D company support

**Comment by bolsoncerrado** [comment]
I dont think it may be a direct cause of "Simplify3D" not working correctly as the gcodes not opening correctly are the ones "altered" by the script, hence they won't be providing support on this....

**Comment by bolsoncerrado** [comment]
I'm gonna open a "bug" report on S3D community but I'm not sure if they'll hear... they're very sensitive with people messing their gcodes.... weirdly enough.

**Comment by bolsoncerrado** [comment]
We'll see:
https://forum.simplify3d.com/viewtopic.php?t=16873

**Comment by bolsoncerrado** [comment]
Just for the record the thumbnails generated with S3Dv5 upload and display fine. 

The only issue now is I can't open them anymore (.gcode) with S3D.

S3D replied this:

https://forum.simplify3d.com/viewtopic.php?p=64096#p64096

**Comment by bolsoncerrado** [comment]
So @idcrook wdy think about this last comment on the S3D forum? Is it doable?

"have to agree ...the 'standard' is a physically formatted mult-iline graphics.
If anything v4.1.x was at fault for reading a single line incorrectly. BTDT

run any other of the 'free' slicers' and look at the icon code.... it's all multi-line.

p.s. Your included gcode sample did not open/display in my S3D 4.1.2 either
"

**Comment by idcrook** [comment]
the "sample" code is an empty file as far as gcode instruction goes -- it was simply a way to to demonstrate how to test and debug the scripts and its tool dependencies on your machine.

**Comment by idcrook** [comment]
Created  PR #5 on https://github.com/idcrook/s3d-thumbnail-generator-macos/tree/feature_split_base64_lines branch that breaks very long base64 encoded string into multiple lines.

**Comment by bolsoncerrado** [comment]
I renamed the old script to .old
put the new branch in place.
gcode is saved unaltered :???

These are the last lines of the test sample.gcode with the new branch. An empty sample.gcode is generated afterwards:





```
+ /usr/sbin/screencapture -x -o -l19409 /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png
++ /usr/local/bin/identify -ping -format '%[w]' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png
+ winpngdimw=5760
++ /usr/local/bin/identify -ping -format '%[h]' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png
+ winpngdimh=2980
+ [[ 5760 == 5760 ]]
+ [[ 2980 == 2980 ]]
+ RETINA_2X_MODE_DETECTED=1
+ echo RETINA_2X_MODE_DETECTED=1
RETINA_2X_MODE_DETECTED=1
+ cropw=2468
+ croph=1639
+ cropwinset=2016
+ crophinset=298
+ /usr/local/bin/convert /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png -crop 2468x1639+2016+298 /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/cropped.png
+ echo ''
+ /usr/local/bin/convert /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/cropped.png -resize 32x32 /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/sm_thumb.png
+ b64cmd1='/usr/bin/base64 -b 76 -i /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/sm_thumb.png'
+ set +o xtrace
+ /usr/local/bin/convert /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/cropped.png -resize 400x /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/bigthumb.png
++ /usr/local/bin/identify -ping -format '%[w]x%[h]' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/bigthumb.png
+ bigthumbdim=400x266
+ b64cmd2='/usr/bin/base64 -b 76 -i /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/bigthumb.png'
+ set +o xtrace
400x266 65871
+ sed -i '' 's/^/; /' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/base64.txt
+ cat /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/base64.txt 400x469
**cat: 400x469: No such file or directory**
+ mv /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/newFile.gcode 400x469
```

**Comment by idcrook** [comment]
always include the command line you used to invoke. it seems to think the name of the file you are trying to modify is `400x469`

**Comment by bolsoncerrado** [comment]
@idcrook  I used the one as in the example 

% echo END >! sample.gcode && ./generate_S3D_thumbnails.bash 400x469 237992

**Comment by bolsoncerrado** [comment]
Well gave it another go:

alex@Mac-Studio s3d-thumbnails %  echo END >! sample.gcode && ./generate_S3D_thumbnails.bash 400x469 237992
+ SCREENCAPTURE=/usr/sbin/screencapture
+ BASE64=/usr/bin/base64
+ bpfix=/usr/local
+ '[' -x /opt/homebrew/bin/brew ']'
+ GETWINDOWID=/usr/local/bin/GetWindowID
+ CONVERT=/usr/local/bin/convert
+ IDENTIFY=/usr/local/bin/identify
++ dirname ./generate_S3D_thumbnails.bash
+ INSTALL_DIR=./
+ GCODE=400x469
+ WORKDIR=/var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/
+ RETINA_2X_MODE_DETECTED=0
+ DEFAULT_APP_WIDTH=1100
+ DEFAULT_APP_HEIGHT=775
++ shopt -po xtrace
+ TRACESTATE='set -o xtrace'
+ touch ./runtimestamp
+ [[ set -o xtrace == \s\e\t\ \-\o\ \x\t\r\a\c\e ]]
+ echo 400x469 237992
+ echo /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/
+ echo 400x469
++ /usr/local/bin/GetWindowID Simplify3D --list
++ grep Simplify3D
+ winidinfo='"Simplify3D (Licensed to xxxxxxx xxxxxxx)" size=2880x1490 id=1079'
+ '[' 0 -eq 1 ']'
+ [[ "Simplify3D (Licensed to xxxxxxx xxxxxxx)" size=2880x1490 id=1079 =~ size=([0-9]+)x([0-9]+) ]]
+ appwidth=2880
+ appheight=1490
+ [[ "Simplify3D (Licensed to xxxxxxx xxxxxxx)" size=2880x1490 id=1079 =~ id=([0-9]+) ]]
+ winid=1079
+ [[ "Simplify3D (Licensed toxxxxxxx xxxxxxx)" size=2880x1490 id=1079 =~ "([^"]+)" ]]
+ wintitle='Simplify3D (Licensed to xxxxxxx xxxxxxx)'
+ /usr/sbin/screencapture -x -o -l1079 /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png
++ /usr/local/bin/identify -ping -format '%[w]' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png
+ winpngdimw=5760
++ /usr/local/bin/identify -ping -format '%[h]' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png
+ winpngdimh=2980
+ [[ 5760 == 5760 ]]
+ [[ 2980 == 2980 ]]
+ RETINA_2X_MODE_DETECTED=1
+ echo RETINA_2X_MODE_DETECTED=1
RETINA_2X_MODE_DETECTED=1
+ cropw=2468
+ croph=1639
+ cropwinset=2016
+ crophinset=298
+ /usr/local/bin/convert /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/window.png -crop 2468x1639+2016+298 /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/cropped.png
+ echo ''
+ /usr/local/bin/convert /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/cropped.png -resize 32x32 /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/sm_thumb.png
+ b64cmd1='/usr/bin/base64 -b 76 -i /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/sm_thumb.png'
+ set +o xtrace
+ /usr/local/bin/convert /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/cropped.png -resize 400x /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/bigthumb.png
++ /usr/local/bin/identify -ping -format '%[w]x%[h]' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/bigthumb.png
+ bigthumbdim=400x266
+ b64cmd2='/usr/bin/base64 -b 76 -i /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/bigthumb.png'
+ set +o xtrace
400x266 46552
+ sed -i '' 's/^/; /' /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/base64.txt
+ cat /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/base64.txt 400x469
+ mv /var/folders/4n/tmn18bnj68x5qws63j4hlr9m0000gn/T/newFile.gcode 400x469


No error now, but still, a sample.gcode with the word END in it is all I get.

**Comment by idcrook** [comment]
the example cpmmand line to debug from the README (https://github.com/idcrook/s3d-thumbnail-generator-macos#manually-run-script) is

```
echo END >! sample.gcode && ./generate_S3D_thumbnails.bash
```

The reaason why this works is that if no filename argument is given, ithe script assumes a filename of "sample.gcode"

in the command you provided, you are passing the bash command two arguments, `400x469 237992`

the script interprets that first one as a file name  ( `400x469`) for. a gcode file to modify.

**Comment by bolsoncerrado** [comment]
Spoke too soon...

**Comment by bolsoncerrado** [comment]
@idcrook  

So in the command line a sample.gcode works and s3d does not complain opening an empty gcode with just thumbnails in it split in multiple lines.

BUT:

Ran from S3D postprocessing when saving the job to the hard drive produces NO thumbnails at all!

I'm at a loss right now....

**Comment by idcrook** [comment]
I see the same thing running S3D **v5** post-processing script in app (does not appear to work/modify the file).

Running S3D **v4** post-processing does still work, as does running from the command line. 

I cannot really debug the S3D v5 post-processing issue further, as this part of the application is rather opaque. 

I suspect something changed in how post-processing scripts work going from version 4 to version 5? but no idea really. Maybe try the forums again. I can't really do much more for that aspect from this script's side.

**Comment by idcrook** [comment]
I'll merge the branch for multi-line #5

**Comment by bolsoncerrado** [comment]
We shall see...
 https://forum.simplify3d.com/viewtopic.php?t=16948

**Comment by bolsoncerrado** [comment]
WTF! THEY DELETED THE THREAD?!?!

**Comment by idcrook** [comment]
the multi-line base64 encode seems to be working.  changing title on this issue and linking to S3D support issue Re: post-processing script not working in v5

[[[BUG] Postprocessing script not being executed on S3D v5.0.1](https://forum.simplify3d.com/viewtopic.php?t=16955)](https://forum.simplify3d.com/viewtopic.php?t=16955)

**Comment by bolsoncerrado** [comment]
@idcrook so they claim their postprocessing calls work but you say the script is called up to a point? what's the further deal on this? any clue?

**Comment by idcrook** [comment]
I figured out the problem using debugging method. The problem was system permissions.  The application title window name was listing as `"(null)"`. It works again after *deleting* the Simplify3D app from the Screen Recording system permissions.  I added some info to the README about this too. 

I have already pushed the updates to `main` branch.

**Comment by idcrook** [comment]
To re-iterate, this is working fine for me on V5 again after undertaking the system permissions re-allow.

**Comment by bolsoncerrado** [comment]
So you mean to delete the permission, relaunch s3d, make it ask for permission and readd? Or just remove and readd?

**Comment by idcrook** [comment]
toggling the permission switch does not work.  delete it from  the app list, as specifically described. and running the post-process script in S3D will trigger the dialog prompt that will open the Screen Recording permissions app list.  Follow the on-screen instructions.

**Comment by bolsoncerrado** [comment]
Redownloaded script, removed all S3D permissions, readded, now works. 

THANKS!
