### ISSUE TITLE
[FEATURE REQUEST] S3D on MK4 Thumbnail Support?

### ISSUE THREAD

**Issue by bolsoncerrado** [idcrook/s3d-thumbnail-generator-macos#6]
Hi!

Not sure where it actually belongs to but I'll leave the request here!

MK4 thumbmails show up as blurry. Not sure if this can be solved somehow?

THanks!

<img width="936" alt="Captura de pantalla 2023-05-07 a las 12 21 01" src="https://user-images.githubusercontent.com/10992914/236671940-51ea2d19-36eb-4ec9-950a-f9c142f5a5e1.png">

**Comment by idcrook** [comment]
There are actually two thumbnails placed in every file. I suspect that the Prusa app is using the first (much smaller) thumbnail and scaling it.

From a sample file, revealing the two thumbnails.

```shell
$ grep thumbnail xb7_cables_right.gcode
; thumbnail begin 32x32 4380
; thumbnail end
; thumbnail begin 400x254 140768
; thumbnail end
```

**Comment by idcrook** [comment]
Noticed some interesting aspects related to thumbnails in Simplify3D v5.1 just released

[Simplify3D Release Notes](https://www.simplify3d.com/products/simplify3d-software/release-notes/)


- Thumbnail preview images can now be embedded directly within G-Code files including support for different resolutions and formats used by Klipper, OctoPrint, Duet, Qidi Tech, Prusa Research, Creality, Snapmaker, FLSUN, Weedo, Tronxy, FlyingBear, MKS, Lotmaxx, and more


[Version 5.1 – What’s New | Simplify3D Software](https://www.simplify3d.com/products/simplify3d-software/whats-new/version-5-1/)

## Embedded Thumbnail Preview Images

Simplify3D can now embed a thumbnail image of your print directly into exported build files. These images can then be displayed on the printer LCD itself providing useful verification during build setup and printer operation. Simplify3D supports thumbnails with many different formats, resolutions, and settings, enabling compatibility with dozens of popular machines and applications.

**Comment by idcrook** [comment]
I just tried this. It automatically fits image and is overall much nicer!  I'd recommend using the native feature in v5.1

It's enabled in the [Output] tab in Process settings.

And Simplify3D 5.1 also adds machine network support for Octoprint!

**Comment by bolsoncerrado** [comment]
Yes, right on time lol

Ty anyway
